[package]
authors = ["Todd Nguyen"]
edition = "2018"
name = "minecraft-mod-packs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.4"
